'use strict';
var config = require('../config/serverConfig.json');
exports.agentServerIP = config.agentServerIP;
exports.agentServerPort = config.agentServerPort;
exports.chatServerIP = config.chatServerIP;
exports.chatServerPort = config.chatServerPort;
exports.viewServerIP = config.viewServerIP;
exports.viewServerPort = config.viewServerPort;
exports.dbUrl = config.dbUrl;
exports.CHAT_COLLECTION = config.chatCollection;
exports.SESSION_COLLECTION = config.chatSessionCollection;
exports.AGENCY_COLLECTION = config.agencyCollection;
exports.agencyHttpServer = "http://" + config.agentServerIP + ":" + config.agentServerPort;
exports.chatHttpsServer = "https://" + config.chatServerIP + ":" + config.chatServerPort;
exports.viewHttpServer = "http://" + config.viewServerIP + ":" + config.viewServerPort;
var log4js = require('log4js');
log4js.loadAppender('file');
log4js.addAppender(log4js.appenders.file('logs/agentServer.log'), 'agentlog');
log4js.addAppender(log4js.appenders.file('logs/chatServer.log'), 'chatlog');
log4js.addAppender(log4js.appenders.file('logs/viewServer.log'), 'viewlog');
exports.agentLogger = log4js.getLogger('agentlog');
exports.chatLogger = log4js.getLogger('chatlog');
exports.viewLogger = log4js.getLogger('viewlog');
//# sourceMappingURL=globals.js.map